{"title": "Archaeological Milestones in Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6427", "tags": ["inscriptions", "J. Pole", "Mahawamsa", "Prehistory", "Sri Lanka Archaeology", "Stone tools", "Turnour"]}
{"title": "SAARC INTERNATIONAL SEMINAR ON ARCHAEOLOGY OF BUDDHISM RECENT DISCOVERIES IN SOUTH ASIA", "link": "https://www.archaeology.lk/1573", "tags": []}
{"title": "PGIAR Graduate Student Seminar 2011", "link": "https://www.archaeology.lk/1364", "tags": ["Graduate Student Seminar", "Postgraduate Institute of Archaeology. PGIAR"]}
{"title": "Sailing Ships and Temple walls", "link": "https://www.archaeology.lk/6500", "tags": ["Dutch ships", "Kandy", "Natha Devale", "Sail ships", "Somasiri Devendra"]}
{"title": "AN INTRODUCTION TO SRI LANKAN GNEISS AND GRANITE CAVES", "link": "https://www.archaeology.lk/2725", "tags": ["Cave Studies"]}
{"title": "A Gemological Perspective of Gem Beads of Jetavana World Heritage Site, Sri Lanka", "link": "https://www.archaeology.lk/2382", "tags": ["beads", "gems", "Jetavana", "Pathmakumara Jayasingha"]}
{"title": "Geological Background of Some Archaeological Sites of Sri Lanka", "link": "https://www.archaeology.lk/2333", "tags": ["archaeological sites", "Pathmakumara Jayasingha"]}
{"title": "Visualization and Haptic Rendering of Ancient Woodcarvings in Sri Lanka", "link": "https://www.archaeology.lk/1237", "tags": ["Ancient Woodcarvings", "Ashu MARASINGHE", "Haptic Rendering", "Kazunori MIYATA", "R.P.C. Janaka RAJAPAKSE", "Raj SOMADEVA", "Sri Lanka", "Visualization", "Yoshimasa TOKUYAMA"]}
{"title": "Prehistory of Sri Lanka 6: Paleolithic period", "link": "https://www.archaeology.lk/5794", "tags": ["Chandima Bandara Ambanwala", "Paleolithic", "Rajarata University of Sri Lanka", "Siran Deraiyagala", "Sri Lanka"]}
{"title": "Prehistory of Sri Lanka 7 : the Pleistocene flora and fauna of Ratnapura", "link": "https://www.archaeology.lk/5907", "tags": ["Chandima Ambanwala", "Kalum Nalinda Manadendarachchi", "P. E. P. Deraniyagala", "Pleistocene", "Prehistory", "Rathnapura", "Sri Lanka"]}
{"title": "Former Commissioner of Archaeology Dr. Saddhamangala Karunarathna Passed away today", "link": "https://www.archaeology.lk/2551", "tags": ["Commissioner of Archaeology", "Dr. Saddhamangala Karunarathna", "obituary"]}
{"title": "Speleothems in Gneissic Caves of Sri Lanka", "link": "https://www.archaeology.lk/1071", "tags": ["Caves", "Gneissic speleothems", "High Grade Silicate rocks", "Sri Lanka"]}
{"title": "Aboriginal Ecology; finding missing link between prehistoric man and the modern man", "link": "https://www.archaeology.lk/1058", "tags": ["Archaeology", "environment", "human behavior", "Sri Lanka", "Veddah"]}
{"title": "Sailing Ships and Temple walls", "link": "https://www.archaeology.lk/6500", "tags": ["Dutch ships", "Kandy", "Natha Devale", "Sail ships", "Somasiri Devendra"]}
{"title": "Two Arabic Epigraphs found from the Ambalangoda Harbour", "link": "https://www.archaeology.lk/6030", "tags": ["Ambalangoda Harbour", "Arabic Epigraphs", "Dr. Mohamed Sulthan Mohamed Saleem", "Mahinda Karunarathna", "W.M Chandrarathne"]}
{"title": "New Maritime Archaeological discoveries in Eastern Province in Sri Lanka: With special emphasis on Trincomale to Potuvil", "link": "https://www.archaeology.lk/2590", "tags": ["Central Cultural Fund", "Eastern Province", "Maritime Archaeology", "Maritime Archaeology Unit"]}
{"title": "Preliminary assessment of an early historic (2000 year old) shipwreck at Godawaya, Sri Lanka", "link": "https://www.archaeology.lk/1646", "tags": []}
{"title": "Keynote address by Prof. Raj Somadewa at The Annual Research Session 2013 of University of Sabaragamuwa, Sri Lanka", "link": "https://www.archaeology.lk/2932", "tags": ["Lecture", "Prof Raj Somadewa"]}
{"title": "Life in Sri Lankan Archaeology", "link": "https://www.archaeology.lk/5542", "tags": []}
{"title": "Archaeology.lk interviews Dr. H. Nimal Perera", "link": "https://www.archaeology.lk/5568", "tags": ["Archaeology", "H. Nimal Perera", "S.U. Deraniyagala", "Sri Lanka"]}
{"title": "archaeology.lk interviews Dr. Karen Lee from the Smithsonian", "link": "https://www.archaeology.lk/2576", "tags": ["Dr. Karen Lee"]}
{"title": "Important Inscriptions of Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6532", "tags": ["Badulla pillar inscription", "Bhuvenekabahu IV", "Gadaladeniya", "Horabora pillar inscription", "Panakaduwa", "Udaya IV", "Vallipuram Gold Plate inscription", "Vasabha", "Vijayabahu"]}
{"title": "Jethawanaramaya Complex as it looked in 9th Century AD", "link": "https://www.archaeology.lk/1344", "tags": ["Anuradha Piyadasa", "Chandima Ambanwala", "Jethawanaramaya Complex", "Prasad Samarajiva", "Royal Asiatic Society - Sri Lanka", "Visualization"]}
{"title": "Speleological Exploration to Sthreepura Lena Cave at Kuruwita, Sri Lanka", "link": "https://www.archaeology.lk/1170", "tags": ["Alahakoon A.M.D", "cave cricket cave fauna", "cave formations", "Dandeniya A.S", "Dewage D.D", "Elgiriya P", "Hettiaarchchi N", "P Jayasingha", "stalactites", "stalagmites", "Weliange W.S"]}
{"title": "20th Century Historians: Rev. Fr. S G Perera", "link": "https://www.archaeology.lk/6055", "tags": ["Chryshane Mendis", "Historian", "Rev. Fr. S G Perera"]}
{"title": "20th Century Historians : D.W. Ferguson", "link": "https://www.archaeology.lk/5912", "tags": ["Chryshane Mendis", "D.W. Ferguson", "History", "Sri Lanka"]}
{"title": "Kotte Heritage 4: Veherakanda", "link": "https://www.archaeology.lk/6290", "tags": ["Baddegana", "Kotte Heritage", "ruins", "Veherakanda"]}
{"title": "Kotte Heritage 3: The Bastions and Passes", "link": "https://www.archaeology.lk/5962", "tags": ["Bastions", "Chryshane Mendis", "Kotte Heritage", "Passes"]}
{"title": "Kotte Heritage 2: The Ramparts and the Moat", "link": "https://www.archaeology.lk/5706", "tags": ["Angampitiya", "Chryshane Mendis", "HERITAGE", "kabook", "Kotte", "Nissanka Alakesvara", "Parakramabahu VI", "rampart", "Sri Lanka"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6427", "tags": ["inscriptions", "J. Pole", "Mahawamsa", "Prehistory", "Sri Lanka Archaeology", "Stone tools", "Turnour"]}
{"title": "Kotte Heritage 4: Veherakanda", "link": "https://www.archaeology.lk/6290", "tags": ["Baddegana", "Kotte Heritage", "ruins", "Veherakanda"]}
{"title": "Untapped Archaeological Heritage: Muthugala", "link": "https://www.archaeology.lk/6274", "tags": ["Chryshane Mendis", "Exploration", "Mutugala", "Polonnaruwa"]}
{"title": "An Archaeological Study on the Kaduruwela Fortress", "link": "https://www.archaeology.lk/6253", "tags": ["Central Cultural Fund", "Excavation", "Exploration", "Kaduruwela Fort", "Priyantha Susil Kumara Marasinghe"]}
{"title": "The Gates of Kandy: An Archaeo-historical Perspective of Balana", "link": "https://www.archaeology.lk/6170", "tags": ["Archaeological Survey", "Balana", "Chryshane Mendis", "Fort", "Gates of Kandy", "Kandyan Kingdom"]}
{"title": "Kotte Heritage 3: The Bastions and Passes", "link": "https://www.archaeology.lk/5962", "tags": ["Bastions", "Chryshane Mendis", "Kotte Heritage", "Passes"]}
{"title": "Kotte Heritage 2: The Ramparts and the Moat", "link": "https://www.archaeology.lk/5706", "tags": ["Angampitiya", "Chryshane Mendis", "HERITAGE", "kabook", "Kotte", "Nissanka Alakesvara", "Parakramabahu VI", "rampart", "Sri Lanka"]}
{"title": "Kotte Heritage 1: The Tunnels", "link": "https://www.archaeology.lk/5224", "tags": ["Alakeshvara", "Chryshane Mendis", "Kotte Heritage", "Portuguese", "Sri Lanka"]}
{"title": "Truth behind the Prison cell of the last King in Colombo Fort", "link": "https://www.archaeology.lk/6425", "tags": ["Ceylinco House", "Chryshane Mendis", "Colombo Fort", "Colonial history", "Prison cell", "Sri Wickrama Rajasinghe"]}
{"title": "Important Inscriptions of Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6532", "tags": ["Badulla pillar inscription", "Bhuvenekabahu IV", "Gadaladeniya", "Horabora pillar inscription", "Panakaduwa", "Udaya IV", "Vallipuram Gold Plate inscription", "Vasabha", "Vijayabahu"]}
{"title": "Archaeological Sites around Dimbulagala: Part 02", "link": "https://www.archaeology.lk/6392", "tags": ["Ancient paintings", "Dimbulagala", "inscriptions", "Kosgaha Ulpatha", "Molahetiwelagala", "Polonnaruwa", "Pulligoda"]}
{"title": "SAARC Photographic Competition and Exhibition", "link": "https://www.archaeology.lk/2664", "tags": []}
{"title": "Truth behind the Prison cell of the last King in Colombo Fort", "link": "https://www.archaeology.lk/6425", "tags": ["Ceylinco House", "Chryshane Mendis", "Colombo Fort", "Colonial history", "Prison cell", "Sri Wickrama Rajasinghe"]}
{"title": "Archaeological Sites around Dimbulagala: Part 02", "link": "https://www.archaeology.lk/6392", "tags": ["Ancient paintings", "Dimbulagala", "inscriptions", "Kosgaha Ulpatha", "Molahetiwelagala", "Polonnaruwa", "Pulligoda"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 02", "link": "https://www.archaeology.lk/6452", "tags": ["Archaeology Survey of Ceylon", "H.C.P. Bell", "Kegalla", "Sigiriya"]}
{"title": "Archaeological Sites around Dimbulagala: Part 01", "link": "https://www.archaeology.lk/6334", "tags": ["Dimbulagala", "Mara Vidiya", "Namal Pokuna", "Pandukabaya", "Sundera Maha Devi"]}
{"title": "Kotte Heritage 4: Veherakanda", "link": "https://www.archaeology.lk/6290", "tags": ["Baddegana", "Kotte Heritage", "ruins", "Veherakanda"]}
{"title": "Untapped Archaeological Heritage: Muthugala", "link": "https://www.archaeology.lk/6274", "tags": ["Chryshane Mendis", "Exploration", "Mutugala", "Polonnaruwa"]}
{"title": "An Archaeological Study on the Kaduruwela Fortress", "link": "https://www.archaeology.lk/6253", "tags": ["Central Cultural Fund", "Excavation", "Exploration", "Kaduruwela Fort", "Priyantha Susil Kumara Marasinghe"]}
{"title": "Kotte Heritage 3: The Bastions and Passes", "link": "https://www.archaeology.lk/5962", "tags": ["Bastions", "Chryshane Mendis", "Kotte Heritage", "Passes"]}
{"title": "Kotte Heritage 2: The Ramparts and the Moat", "link": "https://www.archaeology.lk/5706", "tags": ["Angampitiya", "Chryshane Mendis", "HERITAGE", "kabook", "Kotte", "Nissanka Alakesvara", "Parakramabahu VI", "rampart", "Sri Lanka"]}
{"title": "Kotte Heritage 1: The Tunnels", "link": "https://www.archaeology.lk/5224", "tags": ["Alakeshvara", "Chryshane Mendis", "Kotte Heritage", "Portuguese", "Sri Lanka"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 02", "link": "https://www.archaeology.lk/6452", "tags": ["Archaeology Survey of Ceylon", "H.C.P. Bell", "Kegalla", "Sigiriya"]}
{"title": "An Archaeological Study on the Kaduruwela Fortress", "link": "https://www.archaeology.lk/6253", "tags": ["Central Cultural Fund", "Excavation", "Exploration", "Kaduruwela Fort", "Priyantha Susil Kumara Marasinghe"]}
{"title": "Two Arabic Epigraphs found from the Ambalangoda Harbour", "link": "https://www.archaeology.lk/6030", "tags": ["Ambalangoda Harbour", "Arabic Epigraphs", "Dr. Mohamed Sulthan Mohamed Saleem", "Mahinda Karunarathna", "W.M Chandrarathne"]}
{"title": "Excavating Alugalge: archaeology.lk visits the excavations of the prehistoric site", "link": "https://www.archaeology.lk/5510", "tags": ["Alugalge", "Balangoda", "Chryshane Mendis", "Field Archaeology Unit", "Illukumbura", "National Science Foundation (NSF)", "Postgraduate Institute of Archaeology. PGIAR", "Raj SOMADEVA", "Rathnapura"]}
{"title": "Study of Holocene hunter-gatherers in Sri Lanka : towards a regional model", "link": "https://www.archaeology.lk/5339", "tags": ["adaptation", "Holocene", "hunter-gatherers", "Prehistoric", "Sri Lanka"]}
{"title": "Alugalge Cave in Balangoda Revisited", "link": "https://www.archaeology.lk/5283", "tags": ["Alugala Cave", "Balangoda", "Excavation", "Raj Soamdeva"]}
{"title": "Excavating the Royal Palace of Seethawaka", "link": "https://www.archaeology.lk/5249", "tags": []}
{"title": "Udupiyangala excavations, the conclusion", "link": "https://www.archaeology.lk/5087", "tags": []}
{"title": "Fieldwork of  the Hunters in Transition Project -2016 (Second field season)", "link": "https://www.archaeology.lk/5072", "tags": []}
{"title": "Hunugalagala Limestone Cave Excavation 2013", "link": "https://www.archaeology.lk/2376", "tags": ["Excavation", "Hunugalagala", "Limestone Cave", "Postgraduate Institute of Archaeology", "Prof Raj Somadewa"]}
{"title": "Important Inscriptions of Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6532", "tags": ["Badulla pillar inscription", "Bhuvenekabahu IV", "Gadaladeniya", "Horabora pillar inscription", "Panakaduwa", "Udaya IV", "Vallipuram Gold Plate inscription", "Vasabha", "Vijayabahu"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6427", "tags": ["inscriptions", "J. Pole", "Mahawamsa", "Prehistory", "Sri Lanka Archaeology", "Stone tools", "Turnour"]}
{"title": "Two Arabic Epigraphs found from the Ambalangoda Harbour", "link": "https://www.archaeology.lk/6030", "tags": ["Ambalangoda Harbour", "Arabic Epigraphs", "Dr. Mohamed Sulthan Mohamed Saleem", "Mahinda Karunarathna", "W.M Chandrarathne"]}
{"title": "An Epigraphic and Social archaeological study of Vaharala Inscriptions", "link": "https://www.archaeology.lk/5449", "tags": ["inscriptions", "Mangalika Rajapaksha", "Senarat Paranavitana", "Sri Lanka", "Vaharala"]}
{"title": "Truth behind the Prison cell of the last King in Colombo Fort", "link": "https://www.archaeology.lk/6425", "tags": ["Ceylinco House", "Chryshane Mendis", "Colombo Fort", "Colonial history", "Prison cell", "Sri Wickrama Rajasinghe"]}
{"title": "Archaeological Sites around Dimbulagala: Part 01", "link": "https://www.archaeology.lk/6334", "tags": ["Dimbulagala", "Mara Vidiya", "Namal Pokuna", "Pandukabaya", "Sundera Maha Devi"]}
{"title": "Truth behind the Prison cell of the last King in Colombo Fort", "link": "https://www.archaeology.lk/6425", "tags": ["Ceylinco House", "Chryshane Mendis", "Colombo Fort", "Colonial history", "Prison cell", "Sri Wickrama Rajasinghe"]}
{"title": "Sailing Ships and Temple walls", "link": "https://www.archaeology.lk/6500", "tags": ["Dutch ships", "Kandy", "Natha Devale", "Sail ships", "Somasiri Devendra"]}
{"title": "20th Century Historians: Rev. Fr. S G Perera", "link": "https://www.archaeology.lk/6055", "tags": ["Chryshane Mendis", "Historian", "Rev. Fr. S G Perera"]}
{"title": "20th Century Historians : D.W. Ferguson", "link": "https://www.archaeology.lk/5912", "tags": ["Chryshane Mendis", "D.W. Ferguson", "History", "Sri Lanka"]}
{"title": "Fishing Practices in Prehistoric Sri Lanka", "link": "https://www.archaeology.lk/1142", "tags": ["archaeo-fauna", "ethno-ichthyology", "Fishing Practices", "floodplains", "Prehistoric", "prehistoric deposits", "Sri Lanka", "Wasantha S Weliange"]}
{"title": "Re-examination of the interpretations given by Senarat Paranavitana to several literary terms occurring in certain lithic records", "link": "https://www.archaeology.lk/1133", "tags": ["literary terms", "lithic records", "Prof. Sirimal Ranawella", "Senarat Paranavitana", "Sri Lanka"]}
{"title": "archaeology.lk 2&lt;sup&gt;nd&lt;/sup&gt; Anniversary", "link": "https://www.archaeology.lk/1559", "tags": []}
{"title": "Check your knowledge about Sri Lankan Archaeology by answering 10 questions", "link": "https://www.archaeology.lk/6162", "tags": ["Knowledge", "Sri Lankan Archaeology"]}
{"title": "Highway System in Ancient Sri Lanka", "link": "https://www.archaeology.lk/6409", "tags": ["Ancient Road Network", "Ancient Sri Lanka", "gavukanu", "Godavaya port", "Gokanantittha", "Highway System", "Hopitigamuva inscription", "Jambukolapattana", "Lankapattana", "Magama", "Mahatittha", "Mahavamsa", "Malvatu Oya", "Rajarata", "rajaveediya", "Silk Road"]}
{"title": "Scientific evidences to show ancient lead trade with Tissamaharama Sri Lanka: A metallurgical study", "link": "https://www.archaeology.lk/6566", "tags": ["ANCIENT COINS", "ANCIENT METALLURGY", "ANCIENT TRADE", "LEAD", "LEAD ISOTOPE", "Sri Lanka", "TISSAMAHARAMA"]}
{"title": "An evaluation on Scientific Investigation of Bronze Tara image from Sri Lanka at the British Museum: A critical evaluation on controversy of its provenance", "link": "https://www.archaeology.lk/6552", "tags": []}
{"title": "Kandy Period Bronze Buddha Images of Sri Lanka: Visual and Technological Styles", "link": "https://www.archaeology.lk/6494", "tags": ["Arjuna Thantilage", "Laboratory for Cultural Material Analysis", "Postgraduate Institute of Archaeology", "Sri Lanka", "University of Kelaniya"]}
{"title": "Surgery in an ancient kingdom", "link": "https://www.archaeology.lk/1712", "tags": []}
{"title": "Archaeological Sites around Dimbulagala: Part 02", "link": "https://www.archaeology.lk/6392", "tags": ["Ancient paintings", "Dimbulagala", "inscriptions", "Kosgaha Ulpatha", "Molahetiwelagala", "Polonnaruwa", "Pulligoda"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 02", "link": "https://www.archaeology.lk/6452", "tags": ["Archaeology Survey of Ceylon", "H.C.P. Bell", "Kegalla", "Sigiriya"]}
{"title": "Archaeological Sites around Dimbulagala: Part 01", "link": "https://www.archaeology.lk/6334", "tags": ["Dimbulagala", "Mara Vidiya", "Namal Pokuna", "Pandukabaya", "Sundera Maha Devi"]}
{"title": "Archaeological Milestones in Sri Lanka: Part 01", "link": "https://www.archaeology.lk/6427", "tags": ["inscriptions", "J. Pole", "Mahawamsa", "Prehistory", "Sri Lanka Archaeology", "Stone tools", "Turnour"]}
{"title": "Martello Tower, Hambantota", "link": "https://www.archaeology.lk/5791", "tags": ["Dhanesh Wisumperuma", "Hambantota", "Martello Tower"]}
